plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "exe/**/*"
    - "sig/**/*"
    - "vendor/**/*"

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true

Minitest/MultipleAssertions:
  Max: 1

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "lib/riffer/rig/version.rb"

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self
