# RBS's stdlib `open3` signatures omit popen2e.

module Open3
  def self?.popen2e: (*String, ?unsetenv_others: bool, ?pgroup: true | Integer, ?umask: Integer, ?close_others: bool, ?chdir: String) -> [IO, IO, Process::Waiter]
end
